### ISSUE TITLE
[v9] Sale Order Type Invoicing Policy: not able to finish the install procedure

### ISSUE THREAD

**Issue by BzMB** [ingadhoc/sale#77]
Hi,

The installation of the module "Sale Order Type Invoicing Policy" stops with the following message:
```
ParseError: "null value in column "warehouse_id" violates not-null constraint
DETAIL:  Failing row contains (2, null, 1, 2017-06-18 19:19:03.303221, null, direct, null, 1, null, null, 2017-06-18 19:19:03.303221, null, null, null, Pre Paid, prepaid).
" while parsing /opt/o9c/community/ingadhoc_sale/sale_order_type_invoice_policy/data/sale_order_type_data.xml:3, near
<record id="prepaid_sale_type" model="sale.order.type">
            <field name="name">Pre Paid</field>
            <field name="invoice_policy">prepaid</field>
        </record>
```

extra addons paths loaded:
ingadhoc_sale
ingadhoc_account-payment
ingadhoc_stock
OCA_account-invoicing

Any Ideas?

**Comment by jjscarafia** [comment]
Buenas, probé recién correr una nueva build en [runbot](http://runbot2.adhoc.com.ar/runbot/repo/git-github-com-ingadhoc-sale-git-8) y parece instalar bien.
Además lo venimos usando en varios clientes, sospecho que el error debe venir por otro lado o compatibilidad con algún otro módulo
